# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
# hint: import … as
import numpy as np

In [3]:
#### 2. Create a null vector of size 10 (★☆☆)
# hint: np.zeros

vector_a = np.zeros((10))
print(vector_a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [24]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
# hint: array[4]

vector_a[0, 4] = 1
print(vector_a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [27]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
# hint: arange

vector_b = np.arange(10, 50)
print(vector_b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
# hint: reshape

matrix_a = np.arange(0, 9).reshape((3, 3))
print(matrix_a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [34]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
# hint: np.nonzero

vector_c = [1,2,0,0,4,0]
non_zero = np.nonzero(vector_c)
print(non_zero)

(array([0, 1, 4], dtype=int64),)


In [38]:
#### 7. Create a 3x3 identity matrix (★☆☆)
# hint: np.eye

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
# hint: np.random.random

matrix_b = np.random.random((3, 3, 3))
print(matrix_b)

[[[0.06600409 0.54370835 0.45033048]
  [0.48340214 0.55580969 0.08902109]
  [0.96933652 0.55631523 0.94738405]]

 [[0.80737749 0.32229999 0.73462748]
  [0.84188986 0.83341971 0.34540453]
  [0.20128383 0.39794978 0.11513558]]

 [[0.84463205 0.65820297 0.11596696]
  [0.80566147 0.58203428 0.95781657]
  [0.31738105 0.21152842 0.2335294 ]]]


In [58]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
# hint: min, max`

matrix_c = np.random.random((10, 10))
print(matrix_c)
print(matrix_c.min())
print(matrix_c.max())

[[0.47068443 0.60746799 0.8096041  0.42940065 0.83594134 0.15938753
  0.14482959 0.16049042 0.48570475 0.46771597]
 [0.43097358 0.58423983 0.70507902 0.31091028 0.09756889 0.28815905
  0.63973605 0.06174549 0.1593118  0.86074058]
 [0.36269766 0.07102412 0.33485886 0.59178006 0.38295407 0.77995931
  0.41502357 0.58014304 0.81407124 0.92626555]
 [0.90553794 0.89805583 0.89238744 0.11965634 0.4578432  0.91673488
  0.50368936 0.98891526 0.19860384 0.29972605]
 [0.49437603 0.18043406 0.49215115 0.90234771 0.82048425 0.56931078
  0.83228232 0.43859371 0.09301511 0.81153324]
 [0.39024218 0.83668191 0.83347056 0.0599012  0.80801351 0.12700351
  0.30922041 0.74252791 0.36234144 0.69920193]
 [0.69227054 0.81828018 0.26766744 0.60502514 0.94881377 0.31879953
  0.324539   0.69954474 0.20556599 0.0124203 ]
 [0.88224216 0.86813179 0.32541237 0.35772098 0.68486538 0.73165552
  0.10119079 0.14847049 0.25058078 0.61155084]
 [0.71062598 0.443735   0.10423704 0.11818276 0.53484704 0.30721772
  0.10593728

In [60]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
# hint: mean

vector_c = np.random.random((30))
print(vector_c)
print(vector_c.mean())

[0.38274502 0.50191537 0.80933115 0.30708801 0.27203347 0.06542975
 0.73332183 0.58784705 0.33242357 0.51917937 0.39978198 0.92464042
 0.99183727 0.48966694 0.92059108 0.64603362 0.20388284 0.92326706
 0.39942129 0.23759663 0.64541356 0.70993607 0.18157925 0.3826115
 0.61179453 0.72724285 0.54255392 0.97001692 0.80626448 0.92466749]
0.5716704765894682


In [6]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
# hint: np.diag

lst = [9, 0, 9, 2, 4], [4, 5, 1, 9, 0], [1, 0, 8, 3, 2], [1, 7, 8, 2, 0], [4, 8, 1, 9, 0]
matrix_d = np.array(lst)

diagonal = (np.diag([1, 2, 3, 4,], k=-1))

print(diagonal)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [7]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
# hint: (x -mean)/std

matrix_e = np.random.random((5,5))
matrix_e = matrix_e-np.mean(matrix_e)/np.std(matrix_e)
print(matrix_e)

[[-1.23418856 -1.30801288 -1.09142314 -1.52512819 -1.62512715]
 [-1.24598875 -1.5054789  -1.51338325 -1.27286437 -0.93241436]
 [-1.09188586 -1.32155624 -1.61469807 -1.93009051 -1.26474936]
 [-1.6079647  -1.3718213  -1.14918594 -0.96354412 -1.38667075]
 [-1.09889176 -1.8178115  -1.40771902 -1.75970571 -1.92739269]]


In [93]:
#### 13. How to find common values between two arrays? (★☆☆)
# hint: np.intersect1d

new_lst = [9, 1, 10, 2, 4], [4, 5, 12, 9, 0], [1, 0, 4, 5, 2], [1, 9, 8, 4, 0], [6, 8, 1, 9, 0]
matrix_f = np.array(new_lst)

print(np.intersect1d(matrix_d, matrix_f)) # matrix_d is generated in question 11

[0 1 2 4 5 8 9]


In [97]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
# hint: sort

vector_d = np.random.random((10))
vector_d.sort()
print(vector_d)

[0.11085002 0.12950345 0.13693532 0.24949379 0.31128474 0.38611452
 0.47090035 0.52986821 0.81650084 0.83943124]


In [103]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
# hint: argmax
vector_e = np.random.random((10))
print(vector_e)
vector_e[np.argmax(vector_e)] = 0
print(vector_e)

[0.98708577 0.87681363 0.94499194 0.14934568 0.8503019  0.8141299
 0.7350567  0.32040976 0.81450579 0.81422664]
[0.         0.87681363 0.94499194 0.14934568 0.8503019  0.8141299
 0.7350567  0.32040976 0.81450579 0.81422664]


In [105]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
# hint: mean(axis=,keepdims=)
print(matrix_f)

matrix_g = matrix_f - matrix_f.mean(axis=1, keepdims=True)
print(matrix_g)

[[ 9  1 10  2  4]
 [ 4  5 12  9  0]
 [ 1  0  4  5  2]
 [ 1  9  8  4  0]
 [ 6  8  1  9  0]]
[[ 3.8 -4.2  4.8 -3.2 -1.2]
 [-2.  -1.   6.   3.  -6. ]
 [-1.4 -2.4  1.6  2.6 -0.4]
 [-3.4  4.6  3.6 -0.4 -4.4]
 [ 1.2  3.2 -3.8  4.2 -4.8]]


In [17]:
#### 17. How to get the n largest values of an array (★★★)
# Z = np.arange(10000)
# np.random.shuffle(Z)
# n = 5
# hint: np.argsort | np.argpartition`

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

Z[np.argsort(Z)[-n:]]
print(Z)

# To get more information about the function: print(np.argsort.__doc__)

[6357 7608 5419 ... 7693 8603 1122]


In [19]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
# hint: np.where

matrix_h = np.random.randint(0, 10, size = (5,3))
matrix_h =np.where(matrix_h > 4, matrix_h **2, matrix_h)

print(matrix_h)

[[64 25  1]
 [36 36  4]
 [81  0 64]
 [49 49  3]
 [ 1  2 64]]
